# Generated by Django 5.2.17 on 2026-09-13 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('languages', 'Programming Language'), ('frameworks', 'Frameworks & Libraries'), ('tools', 'Tools & Platforms')], default='tools', max_length=20)),
                ('level', models.CharField(choices=[('familiar', 'Familiar'), ('proficient', 'Proficient'), ('advanced', 'Advanced')], default='proficient', max_length=20)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance')], default='full-time', max_length=20),
        ),
    ]
