# Generated by Django 5.2.17 on 2026-09-21 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
        migrations.AddField(
            model_name='skill',
            name='nilai',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
