# Generated by Django 5.2.17 on 2026-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_skill_image_path_remove_skill_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('organization', 'Organization'), ('committee', 'Committee')], default='commitee', max_length=20),
        ),
    ]
